### ISSUE TITLE
comware_install_os(): timeout problem 

### ISSUE THREAD

**Issue by johanreinalda** [HPENetworking/ansible-hpe-cw7#13]
Running the play below against an HPE 5900, running r2432p02, upgrading via this to r2432p05

  - name: Upgrade OS to new firmware
     comware_install_os: username={{ username }} password={{ password }} hostname={{ inventory_hostname }} ipe_package={{ firmware }} delete_ipe=false reboot=no

This throws a timeout error in comware_install_os.py, line 304,   device.execute_staged()
See below for details.

The actual problem is in line 186,187, and can be fixed by increasing the timeout value, as shown her to 10 minutes (600, probably overkill):

186     device = HPCOM7(host=hostname, username=username,
187                     password=password, port=port, timeout=600)

Can we get this "timeout" as a parameter to each "comware_xxxxxx()" call ?
I can provide pull if needed.

Johan

-------
Error reported:

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_xQUwA9/ansible_module_comware_install_os.py", line 337, in <module>
    main()
  File "/tmp/ansible_xQUwA9/ansible_module_comware_install_os.py", line 304, in main
    device.execute_staged()
  File "/usr/lib/python2.7/site-packages/pyhpecw7-0.0.9-py2.7.egg/pyhpecw7/comware.py", line 258, in execute_staged
    rsps.append(run_cmd_func(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/pyhpecw7-0.0.9-py2.7.egg/pyhpecw7/comware.py", line 335, in action
    rsp = self.execute(self.connection.action, [element])
  File "/usr/lib/python2.7/site-packages/pyhpecw7-0.0.9-py2.7.egg/pyhpecw7/comware.py", line 219, in execute
    self.unlock()
  File "/usr/lib/python2.7/site-packages/pyhpecw7-0.0.9-py2.7.egg/pyhpecw7/comware.py", line 288, in unlock
    self.connection.unlock(target)
  File "build/bdist.linux-x86_64/egg/ncclient/manager.py", line 162, in wrapper
  File "build/bdist.linux-x86_64/egg/ncclient/manager.py", line 232, in execute
  File "build/bdist.linux-x86_64/egg/ncclient/operations/lock.py", line 49, in request
  File "build/bdist.linux-x86_64/egg/ncclient/operations/rpc.py", line 343, in _request
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.

fatal: [<REDACTED>.oregonstate.edu.]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_xQUwA9/ansible_module_comware_install_os.py\", line 337, in <module>\n    main()\n  File \"/tmp/ansible_xQUwA9/ansible_module_comware_install_os.py\", line 304, in main\n    device.execute_staged()\n  File \"/usr/lib/python2.7/site-packages/pyhpecw7-0.0.9-py2.7.egg/pyhpecw7/comware.py\", line 258, in execute_staged\n    rsps.append(run_cmd_func(*args, **kwargs))\n  File \"/usr/lib/python2.7/site-packages/pyhpecw7-0.0.9-py2.7.egg/pyhpecw7/comware.py\", line 335, in action\n    rsp = self.execute(self.connection.action, [element])\n  File \"/usr/lib/python2.7/site-packages/pyhpecw7-0.0.9-py2.7.egg/pyhpecw7/comware.py\", line 219, in execute\n    self.unlock()\n  File \"/usr/lib/python2.7/site-packages/pyhpecw7-0.0.9-py2.7.egg/pyhpecw7/comware.py\", line 288, in unlock\n    self.connection.unlock(target)\n  File \"build/bdist.linux-x86_64/egg/ncclient/manager.py\", line 162, in wrapper\n  File \"build/bdist.linux-x86_64/egg/ncclient/manager.py\", line 232, in execute\n  File \"build/bdist.linux-x86_64/egg/ncclient/operations/lock.py\", line 49, in request\n  File \"build/bdist.linux-x86_64/egg/ncclient/operations/rpc.py\", line 343, in _request\nncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
        to retry, use: --limit @/opt/playbooks/5900-upgrade.retry

**Comment by dongzj** [comment]
The default timeout is 150(S) might be too short to install the os.  It is better to add a timeout parameter to each comware_xxx() call.

**Comment by johanreinalda** [comment]
Yes, that would solve the problem.

**Comment by SeasLiV** [comment]
Hello,

I'm facing the same issue with @johanreinalda.
I've been trying to look for any defaults values of "TimeOut" inside each .py files (ansible-hpe-cw7/library/comware_xxx.py) and i saw that the file comware_copy.py is using TimeOut (with the value 120 as default).

I'm trying to use the module "comware_command" so i've edited the file comware_command.py.
I add this value :
```
    device_args = dict(host=hostname, username=username,
                       password=password, port=port, **timeout=500**)

    device = HPCOM7(**device_args)
```
I try to ran the script one more time and still the same TimeOut issue.
I try to edit this file rpc.py. (I've find this file from my error message)
(/var/lib/awx/venv/"venvname"/lib/python2.7/site-packages/ncclient/operations/rpc.py)

I've increase the the default value of the "TimeOut" (from 30 to 500) but still the same issue.
Now i'm kinda stuck... any idea of how to increase the TimeOut value ?

Regards,
SeasLIV
