### ISSUE TITLE
I'm having issue with running comware_command on 5900

### ISSUE THREAD

**Issue by liorfranko** [HPENetworking/ansible-hpe-cw7#9]
System image version: 7.1.045, Release 2311P01
Hardware:
5900AF-48XGT-4QSFP+

This is the Ansible task I'm running:
- name: COMWARE - backup running-config from comware device
  comware_command:
    command:
      - display current-configuration
    type: display
    username: "{{ username }}"
    password: "{{ password }}"
    hostname: "{{ inventory_hostname }}"

Output:
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/var/folders/6t/t1thtkqx0gsbv6gd1dykbbx4vb87_3/T/ansible_DjGWwt/ansible_module_comware_command.py", line 186, in <module>
    main()
  File "/var/folders/6t/t1thtkqx0gsbv6gd1dykbbx4vb87_3/T/ansible_DjGWwt/ansible_module_comware_command.py", line 169, in main
    response = device.cli_config(command)
  File "/Library/Python/2.7/site-packages/pyhpecw7/comware.py", line 385, in cli_config
    rsp = self.execute(self.connection.cli_config, [command])
  File "/Library/Python/2.7/site-packages/pyhpecw7/comware.py", line 207, in execute
    self.lock()
  File "/Library/Python/2.7/site-packages/pyhpecw7/comware.py", line 268, in lock
    self.connection.lock(target)
  File "/Library/Python/2.7/site-packages/ncclient/manager.py", line 162, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/Library/Python/2.7/site-packages/ncclient/manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/Library/Python/2.7/site-packages/ncclient/operations/lock.py", line 35, in request
    return self._request(node)
  File "/Library/Python/2.7/site-packages/ncclient/operations/rpc.py", line 326, in _request
    raise self._error
Exception

fatal: [HOSTNAME]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "comware_command"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/6t/t1thtkqx0gsbv6gd1dykbbx4vb87_3/T/ansible_DjGWwt/ansible_module_comware_command.py\", line 186, in <module>\n    main()\n  File \"/var/folders/6t/t1thtkqx0gsbv6gd1dykbbx4vb87_3/T/ansible_DjGWwt/ansible_module_comware_command.py\", line 169, in main\n    response = device.cli_config(command)\n  File \"/Library/Python/2.7/site-packages/pyhpecw7/comware.py\", line 385, in cli_config\n    rsp = self.execute(self.connection.cli_config, [command])\n  File \"/Library/Python/2.7/site-packages/pyhpecw7/comware.py\", line 207, in execute\n    self.lock()\n  File \"/Library/Python/2.7/site-packages/pyhpecw7/comware.py\", line 268, in lock\n    self.connection.lock(target)\n  File \"/Library/Python/2.7/site-packages/ncclient/manager.py\", line 162, in wrapper\n    return self.execute(op_cls, *args, **kwds)\n  File \"/Library/Python/2.7/site-packages/ncclient/manager.py\", line 232, in execute\n    raise_mode=self._raise_mode).request(*args, **kwds)\n  File \"/Library/Python/2.7/site-packages/ncclient/operations/lock.py\", line 35, in request\n    return self._request(node)\n  File \"/Library/Python/2.7/site-packages/ncclient/operations/rpc.py\", line 326, in _request\n    raise self._error\nException\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}

This is the output of manual test I'm running from python:
liorf-mac:Sessions liorf$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyhpecw7.comware import HPCOM7
>>> args = dict(host='HOSTNAME', username='username', password='password', port=830)
>>> device = HPCOM7(**args)
>>> device.open()
<ncclient.manager.Manager object at 0x10d0abfd0>
>>> device.connected
True
>>>

**Comment by liorfranko** [comment]
Anyone?????

**Comment by dongzj** [comment]
The problem did not occur in my environment. Have you tried any other commands?
